version: '3'
services:

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    working_dir: /application
    volumes:
        - .:/application
        - ./db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306    
    networks:
      - keycloak-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
        - mysql
    links: 
        - mysql
    ports:
        - 8082:80
    environment:
        PMA_HOST: mysql
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_ROOT_PASSWORD: admin
        UPLOAD_LIMIT: 1G
    restart: always
    networks:
        - keycloak-network
  
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8080:8080
    restart: always
    environment:
      - DB_VENDOR=mysql
      - DB_ADDR=mysql
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=keycloak
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    depends_on:
      - mysql
    networks:
      - keycloak-network
        
networks:
  keycloak-network:
    driver: bridge
